include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

linter:
  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: false
    unawaited_futures: false
    prefer_single_quotes: false
    unnecessary_this: false
    omit_local_variable_types: false
    always_declare_return_types: false
    prefer_final_fields: false