name: responsive_table
description: Responsive Data table is a highly flexible tool built upon the foundations of progressive enhancement, that adds all of these advanced features to any flutter table.
version: 0.2.0+2
homepage: https://github.com/kechankrisna/flutter_responsive_table

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  adaptivex: ^0.0.1+2
  flutter:
    sdk: flutter  
  get: ^4.6.6
  provider: ^6.1.2
 

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: